export const TYPES = [
  {
    id: 'melkesjokolade',
    label: 'Melkesjokolade (200 g)',
    price: 71,
    image: 'https://assets.kvass.no/693948b68e71ee11b9336ce2',
  },
  {
    id: 'daim',
    label: 'Smak av Daim (200 g)',
    price: 71,
    image: 'https://assets.kvass.no/69394bf48e71ee11b9336fdf',
  },
  {
    id: 'kvikklunsj',
    label: 'Smak av Kvikklunsj (200 g)',
    price: 71,
    image: 'https://assets.kvass.no/69394c078e71ee11b9336feb',
  },
  {
    id: 'firkløver',
    label: 'Firkløver (200 g)',
    price: 71,
    image: 'https://assets.kvass.no/69394c178e71ee11b933701a',
  },
]

export const CATEGORIES = [
  {
    id: 'merkedager',
    label: 'Merkedager og anledninger',
    count: 9,
    icon: 'https://assets.kvass.no/693888f44a6bbc745f6a1ea9',
  },
  {
    id: 'kjærlighet',
    label: 'Kjærlighet',
    count: 5,
    icon: 'https://assets.kvass.no/693889b84a6bbc745f6a1fab',
  },
  {
    id: 'familie',
    label: 'Familie og vennskap',
    count: 4,
    icon: 'https://assets.kvass.no/693889e24a6bbc745f6a203e',
  },
  {
    id: 'underholdning',
    label: 'Underholdning',
    count: 5,
    icon: 'https://assets.kvass.no/69388a154a6bbc745f6a213e',
  },
]

// {
//   id: '',
//   message: '',
//   type: 'melkesjokolade',
//   category: '',
//   price: 71,
//   image: '',
// }

export const PRODUCTS = [
  {
    id: 'M04_Freia_200G_Packtivation_Melkesjokolade_EMOJI',
    message: 'Den som sender hjerter',
    type: 'melkesjokolade',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945d5eae4edea6640e61678',
  },
  {
    id: 'M05_Freia_200G_Packtivation_Melkesjokolade_FORSINKA',
    message: 'Den som inviterer',
    type: 'melkesjokolade',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945d5eae4edea6640e61684',
  },
  {
    id: 'M07_Freia_200G_Packtivation_Melkesjokolade_GOSSIP',
    message: 'Den som tok med gossip',
    type: 'melkesjokolade',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945d5eae4edea6640e61690',
  },
  {
    id: 'M10_Freia_200G_Packtivation_Melkesjokolade_HUNDEN',
    message: 'Den som passet hunden',
    type: 'melkesjokolade',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945d5eae4edea6640e6169c',
  },
  {
    id: 'M03_Freia_200G_Packtivation_Melkesjokolade_ELSKER_DEG',
    message: 'Den som sa "jeg elsker deg" først',
    type: 'melkesjokolade',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945d9f2e4edea6640e61a63',
  },
  {
    id: 'M08_Freia_200G_Packtivation_Melkesjokolade_HADDE_RETT',
    message: 'Den som hadde helt rett',
    type: 'melkesjokolade',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945d9f2e4edea6640e61a6f',
  },
  {
    id: 'M09_Freia_200G_Packtivation_Melkesjokolade_HALVDEL',
    message: 'Til min bedre halvdel',
    type: 'melkesjokolade',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945d9f2e4edea6640e61a7b',
  },
  {
    id: 'M17_Freia_200G_Packtivation_Melkesjokolade_ONDE_DAGER',
    message: 'I gode dager',
    type: 'melkesjokolade',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945d9f2e4edea6640e61a87',
  },
  {
    id: 'M23_Freia_200G_Packtivation_Melkesjokolade_Verdens_BESTE',
    message: 'Verdens beste',
    type: 'melkesjokolade',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945d9f3e4edea6640e61a93',
  },
  {
    id: 'M01_Freia_200G_Packtivation_Melkesjokolade_BAKE',
    message: 'Den som bakte kake',
    type: 'melkesjokolade',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945dc07e4edea6640e61c41',
  },
  {
    id: 'M02_Freia_200G_Packtivation_Melkesjokolade_BURSDAG',
    message: 'Den som har bursdag',
    type: 'melkesjokolade',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945dc07e4edea6640e61c4d',
  },
  {
    id: 'M06_Freia_200G_Packtivation_Melkesjokolade_FROKOST_SENGA',
    message: 'Den som fikk frokost på senga',
    type: 'melkesjokolade',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945dc07e4edea6640e61c59',
  },
  {
    id: 'M12_Freia_200G_Packtivation_Melkesjokolade_KVINNEDAGEN',
    message: 'Verdens beste dame',
    type: 'melkesjokolade',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945dc07e4edea6640e61c65',
  },
  {
    id: 'M13_Freia_200G_Packtivation_Melkesjokolade_MORSDAG',
    message: 'Verdens beste mamma - morsdag',
    type: 'melkesjokolade',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945dc08e4edea6640e61c71',
  },
  {
    id: 'M14_Freia_200G_Packtivation_Melkesjokolade_MORSDAG2',
    message: 'Verdens beste mamma - sønn',
    type: 'melkesjokolade',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945dc08e4edea6640e61c7d',
  },
  {
    id: 'M15_Freia_200G_Packtivation_Melkesjokolade_MORSDAG3',
    message: 'Verdens beste mamma - datter',
    type: 'melkesjokolade',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945dc08e4edea6640e61c89',
  },
  {
    id: 'M20_Freia_200G_Packtivation_Melkesjokolade_SAMEDAGEN',
    message: 'Den som hjelper med koftesølvet',
    type: 'melkesjokolade',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945dc08e4edea6640e61c95',
  },
  {
    id: 'M22_Freia_200G_Packtivation_Melkesjokolade_VALENTINE',
    message: 'Verdens beste kjæreste',
    type: 'melkesjokolade',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945dc08e4edea6640e61ca1',
  },
  {
    id: 'M11_Freia_200G_Packtivation_Melkesjokolade_KONKURRANSE',
    message: 'Det største konkurransemennesket',
    type: 'melkesjokolade',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945df53e4edea6640e61f19',
  },
  {
    id: 'M16_Freia_200G_Packtivation_Melkesjokolade_NYTTÅRSFORSETT',
    message: 'Den som gjennomfører nyttårsforsettet',
    type: 'melkesjokolade',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945df53e4edea6640e61f25',
  },
  {
    id: 'M18_Freia_200G_Packtivation_Melkesjokolade_QUIZ',
    message: 'Den som vant quizen',
    type: 'melkesjokolade',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945df53e4edea6640e61f31',
  },
  {
    id: 'M19_Freia_200G_Packtivation_Melkesjokolade_REVANSJ',
    message: 'Den som vant',
    type: 'melkesjokolade',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945df53e4edea6640e61f3d',
  },
  {
    id: 'M21_Freia_200G_Packtivation_Melkesjokolade_TV_SPORT',
    message: 'Den som velger sport på tv`en',
    type: 'melkesjokolade',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945df53e4edea6640e61f49',
  },
  {
    id: 'D04_Freia_200G_Packtivation_Melkesjokolade_Daim_EMOJI',
    message: 'Den som sender hjerter',
    type: 'daim',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945e5bbe4edea6640e62268',
  },
  {
    id: 'D05_Freia_200G_Packtivation_Melkesjokolade_Daim_FORSINKA',
    message: 'Den som inviterer',
    type: 'daim',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945e5bbe4edea6640e62274',
  },
  {
    id: 'D07_Freia_200G_Packtivation_Melkesjokolade_Daim_GOSSIP',
    message: 'Den som tok med gossip',
    type: 'daim',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945e5bbe4edea6640e62280',
  },
  {
    id: 'D10_Freia_200G_Packtivation_Melkesjokolade_Daim_HUNDEN',
    message: 'Den som passet hunden',
    type: 'daim',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945e5bbe4edea6640e6228c',
  },
  {
    id: 'D03_Freia_200G_Packtivation_Melkesjokolade_Daim_ELSKER_DEG',
    message: 'Den som sa "jeg elsker deg" først',
    type: 'daim',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945e9e4e4edea6640e62539',
  },
  {
    id: 'D08_Freia_200G_Packtivation_Melkesjokolade_Daim_HADDE_RETT',
    message: 'Den som hadde helt rett',
    type: 'daim',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945e9e4e4edea6640e62545',
  },
  {
    id: 'D09_Freia_200G_Packtivation_Melkesjokolade_Daim_HALVDEL',
    message: 'Til min bedre halvdel',
    type: 'daim',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945e9e4e4edea6640e62551',
  },
  {
    id: 'D17_Freia_200G_Packtivation_Melkesjokolade_Daim_ONDE_DAGER',
    message: 'I gode dager',
    type: 'daim',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945e9e4e4edea6640e6255d',
  },
  {
    id: 'D23_Freia_200G_Packtivation_Melkesjokolade_Daim_VERDENS_BESTE',
    message: 'Verdens beste',
    type: 'daim',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945e9e4e4edea6640e62569',
  },
  {
    id: 'D01_Freia_200G_Packtivation_Melkesjokolade_Daim_BAKE',
    message: 'Den som bakte kake',
    type: 'daim',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945eea2e4edea6640e6280f',
  },
  {
    id: 'D02_Freia_200G_Packtivation_Melkesjokolade_Daim_BURSDAG',
    message: 'Den som har bursdag',
    type: 'daim',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945eea2e4edea6640e6281b',
  },
  {
    id: 'D06_Freia_200G_Packtivation_Melkesjokolade_Daim_FROKOST_SENGA',
    message: 'Den som fikk frokost på senga',
    type: 'daim',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945eea2e4edea6640e62827',
  },
  {
    id: 'D12_Freia_200G_Packtivation_Melkesjokolade_Daim_KVINNEDAGEN',
    message: 'Verdens beste dame',
    type: 'daim',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945eea2e4edea6640e62833',
  },
  {
    id: 'D13_Freia_200G_Packtivation_Melkesjokolade_Daim_MORSDAG',
    message: 'Verdens beste mamma - morsdag',
    type: 'daim',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945eea3e4edea6640e6283f',
  },
  {
    id: 'D14_Freia_200G_Packtivation_Melkesjokolade_Daim_MORSDAG2',
    message: 'Verdens beste mamma - sønn',
    type: 'daim',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945eea3e4edea6640e6284b',
  },
  {
    id: 'D15_Freia_200G_Packtivation_Melkesjokolade_Daim_MORSDAG3',
    message: 'Verdens beste mamma - datter',
    type: 'daim',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945eea3e4edea6640e62857',
  },
  {
    id: 'D20_Freia_200G_Packtivation_Melkesjokolade_Daim_SAMEDAGEN',
    message: 'Den som hjelper med koftesølvet',
    type: 'daim',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945eea3e4edea6640e62863',
  },
  {
    id: 'D22_Freia_200G_Packtivation_Melkesjokolade_Daim_VALENTINE',
    message: 'Verdens beste kjæreste',
    type: 'daim',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945eea3e4edea6640e6286f',
  },
  {
    id: 'D11_Freia_200G_Packtivation_Melkesjokolade_Daim_KONKURRANSE',
    message: 'Det største konkurransemennesket',
    type: 'daim',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f0cee4edea6640e62a56',
  },
  {
    id: 'D16_Freia_200G_Packtivation_Melkesjokolade_Daim_NYTTÅRSFORSET',
    message: 'Den som gjennomfører nyttårsforsettet',
    type: 'daim',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f0cee4edea6640e62a62',
  },
  {
    id: 'D18_Freia_200G_Packtivation_Melkesjokolade_Daim_QUIZ',
    message: 'Den som vant quizen',
    type: 'daim',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f0cee4edea6640e62a6e',
  },
  {
    id: 'D19_Freia_200G_Packtivation_Melkesjokolade_Daim_REVANSJ',
    message: 'Den som vant',
    type: 'daim',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f0cee4edea6640e62a7a',
  },
  {
    id: 'D21_Freia_200G_Packtivation_Melkesjokolade_Daim_TV_SPORT',
    message: 'Den som velger sport på tv`en',
    type: 'daim',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f0cee4edea6640e62a86',
  },
  {
    id: 'K04_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_EMOJI',
    message: 'Den som sender hjerter',
    type: 'kvikklunsj',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945f3a7e4edea6640e62b7a',
  },
  {
    id: 'K05_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_FORSINKA',
    message: 'Den som inviterer',
    type: 'kvikklunsj',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945f3a7e4edea6640e62b86',
  },
  {
    id: 'K07_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_GOSSIP',
    message: 'Den som tok med gossip',
    type: 'kvikklunsj',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945f3a7e4edea6640e62b92',
  },
  {
    id: 'K10_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_HUNDEN',
    message: 'Den som passet hunden',
    type: 'kvikklunsj',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945f3a7e4edea6640e62b9e',
  },
  {
    id: 'K03_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_ELSKER_DEG',
    message: 'Den som sa "jeg elsker deg" først',
    type: 'kvikklunsj',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f48be4edea6640e62cdf',
  },
  {
    id: 'K08_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_HADDE_RETT',
    message: 'Den som hadde helt rett',
    type: 'kvikklunsj',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f48be4edea6640e62ceb',
  },
  {
    id: 'K09_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_HALVDEL',
    message: 'Til min bedre halvdel',
    type: 'kvikklunsj',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f48be4edea6640e62cf7',
  },
  {
    id: 'K17_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_ONDE_DAGER',
    message: 'I gode dager',
    type: 'kvikklunsj',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f48be4edea6640e62d03',
  },
  {
    id: 'K23_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_VERDENS_BESTE',
    message: 'Verdens beste',
    type: 'kvikklunsj',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f48be4edea6640e62d0f',
  },
  {
    id: 'K01_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_BAKE',
    message: 'Den som bakte kake',
    type: 'kvikklunsj',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f56fe4edea6640e62e38',
  },
  {
    id: 'K02_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_BURSDAG',
    message: 'Den som har bursdag',
    type: 'kvikklunsj',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f56fe4edea6640e62e44',
  },
  {
    id: 'K06_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_FROKOST_SENGA',
    message: 'Den som fikk frokost på senga',
    type: 'kvikklunsj',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f56fe4edea6640e62e50',
  },
  {
    id: 'K12_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_KVINNEDAGEN',
    message: 'Verdens beste dame',
    type: 'kvikklunsj',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f56fe4edea6640e62e5c',
  },
  {
    id: 'K13_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_MORSDAG',
    message: 'Verdens beste mamma - morsdag',
    type: 'kvikklunsj',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f56fe4edea6640e62e68',
  },
  {
    id: 'K14_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_MORSDAG2',
    message: 'Verdens beste mamma - sønn',
    type: 'kvikklunsj',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f56fe4edea6640e62e74',
  },
  {
    id: 'K15_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_MORSDAG3',
    message: 'Verdens beste mamma - datter',
    type: 'kvikklunsj',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f56fe4edea6640e62e80',
  },
  {
    id: 'K20_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_SAMEDAGEN',
    message: 'Den som hjelper med koftesølvet',
    type: 'kvikklunsj',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f56fe4edea6640e62e8c',
  },
  {
    id: 'K22_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_VALENTINE',
    message: 'Verdens beste kjæreste',
    type: 'kvikklunsj',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f570e4edea6640e62e98',
  },
  {
    id: 'K11_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_KONKURRANSE',
    message: 'Det største konkurransemennesket',
    type: 'kvikklunsj',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f647e4edea6640e62ff9',
  },
  {
    id: 'K16_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_NYTTÅRSFORSETT',
    message: 'Den som gjennomfører nyttårsforsettet',
    type: 'kvikklunsj',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f647e4edea6640e63005',
  },
  {
    id: 'K18_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_QUIZ',
    message: 'Den som vant quizen',
    type: 'kvikklunsj',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f647e4edea6640e63011',
  },
  {
    id: 'K19_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_REVANSJ',
    message: 'Den som vant',
    type: 'kvikklunsj',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f647e4edea6640e6301d',
  },
  {
    id: 'K21_Freia_200G_Packtivation_Melkesjokolade_KvikkLunsj_TV_SPORT',
    message: 'Den som velger sport på tv`en',
    type: 'kvikklunsj',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945f647e4edea6640e63029',
  },
  {
    id: 'F04_Freia_200G_Packtivation_Melkesjokolade_Firkløver_EMOJI',
    message: 'Den som sender hjerter',
    type: 'firkløver',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945f6ebe4edea6640e6310d',
  },
  {
    id: 'F05_Freia_200G_Packtivation_Melkesjokolade_Firkløver_FORSINKA',
    message: 'Den som inviterer',
    type: 'firkløver',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945f6ebe4edea6640e63119',
  },
  {
    id: 'F07_Freia_200G_Packtivation_Melkesjokolade_Firkløver_GOSSIP',
    message: 'Den som tok med gossip',
    type: 'firkløver',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945f6ece4edea6640e63125',
  },
  {
    id: 'F10_Freia_200G_Packtivation_Melkesjokolade_Firkløver_HUNDEN',
    message: 'Den som passet hunden',
    type: 'firkløver',
    category: 'familie',
    price: 71,
    image: 'https://assets.kvass.no/6945f6ece4edea6640e63131',
  },
  {
    id: 'F03_Freia_200G_Packtivation_Melkesjokolade_Firkløver_ELSKER_DEG',
    message: 'Den som sa "jeg elsker deg" først',
    type: 'firkløver',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f7b6e4edea6640e63224',
  },
  {
    id: 'F08_Freia_200G_Packtivation_Melkesjokolade_Firkløver_HADDEE_RETT',
    message: 'Den som hadde helt rett',
    type: 'firkløver',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f7b6e4edea6640e63230',
  },
  {
    id: 'F09_Freia_200G_Packtivation_Melkesjokolade_Firkløver_HALVDEL',
    message: 'Til min bedre halvdel',
    type: 'firkløver',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f7b6e4edea6640e6323c',
  },
  {
    id: 'F17_Freia_200G_Packtivation_Melkesjokolade_Firkløver_ONDE_DAGER',
    message: 'I gode dager',
    type: 'firkløver',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f7b7e4edea6640e63248',
  },
  {
    id: 'F23_Freia_200G_Packtivation_Melkesjokolade_Firkløver_VERDENS_BESTE',
    message: 'Verdens beste',
    type: 'firkløver',
    category: 'kjærlighet',
    price: 71,
    image: 'https://assets.kvass.no/6945f8fae4edea6640e6336a',
  },
  {
    id: 'F01_Freia_200G_Packtivation_Melkesjokolade_Firkløver_BAKE',
    message: 'Den som bakte kake',
    type: 'firkløver',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f8fae4edea6640e63346',
  },
  {
    id: 'F02_Freia_200G_Packtivation_Melkesjokolade_Firkløver_BURSDAG',
    message: 'Den som har bursdag',
    type: 'firkløver',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f8fae4edea6640e63352',
  },
  {
    id: 'F06_Freia_200G_Packtivation_Melkesjokolade_Firkløver_FROKOST_SENGA',
    message: 'Den som fikk frokost på senga',
    type: 'firkløver',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f8fae4edea6640e6335e',
  },
  {
    id: 'F12_Freia_200G_Packtivation_Melkesjokolade_Firkløver_KVINNEDAGEN',
    message: 'Verdens beste dame',
    type: 'firkløver',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f7b7e4edea6640e63254',
  },
  {
    id: 'F13_Freia_200G_Packtivation_Melkesjokolade_Firkløver_MORSDAG',
    message: 'Verdens beste mamma - morsdag',
    type: 'firkløver',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f8fae4edea6640e63376',
  },
  {
    id: 'F14_Freia_200G_Packtivation_Melkesjokolade_Firkløver_MORSDAG2',
    message: 'Verdens beste mamma - sønn',
    type: 'firkløver',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f8fae4edea6640e63382',
  },
  {
    id: 'F15_Freia_200G_Packtivation_Melkesjokolade_Firkløver_MORSDAG3',
    message: 'Verdens beste mamma - datter',
    type: 'firkløver',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f8fae4edea6640e6338e',
  },
  {
    id: 'F20_Freia_200G_Packtivation_Melkesjokolade_Firkløver_SAMEDAGEN',
    message: 'Den som hjelper med koftesølvet',
    type: 'firkløver',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f8fae4edea6640e6339a',
  },
  {
    id: 'F22_Freia_200G_Packtivation_Melkesjokolade_Firkløver_VALENTINE',
    message: 'Verdens beste kjæreste',
    type: 'firkløver',
    category: 'merkedager',
    price: 71,
    image: 'https://assets.kvass.no/6945f8fae4edea6640e633a6',
  },
  //----------------------------------------------------------
  {
    id: 'F11_Freia_200G_Packtivation_Melkesjokolade_Firkløver_KONKURRANSE',
    message: 'Det største konkurransemennesket',
    type: 'firkløver',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945fa56e4edea6640e63499',
  },
  {
    id: 'F16_Freia_200G_Packtivation_Melkesjokolade_Firkløver_NYTTÅRSFORSETT',
    message: 'Den som gjennomfører nyttårsforsettet',
    type: 'firkløver',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945fa56e4edea6640e634a5',
  },
  {
    id: 'F18_Freia_200G_Packtivation_Melkesjokolade_Firkløver_QUIZ',
    message: 'Den som vant quizen',
    type: 'firkløver',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945fa56e4edea6640e634b1',
  },
  {
    id: 'F19_Freia_200G_Packtivation_Melkesjokolade_Firkløver_REVANSJ',
    message: 'Den som vant',
    type: 'firkløver',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945fa56e4edea6640e634bd',
  },
  {
    id: 'F21_Freia_200G_Packtivation_Melkesjokolade_Firkløver_TV_SPORT',
    message: 'Den som velger sport på tv`en',
    type: 'firkløver',
    category: 'underholdning',
    price: 71,
    image: 'https://assets.kvass.no/6945fa56e4edea6640e634c9',
  },
]
